PHONY: run-simple run-react run-tool-calling run-agent

run-simple:
	uv run  chapter-1/simple_llm_call.py

run-react:
	uv run chapter-2/react_agent.py

run-tool-calling:
	uv run chapter-3/function_calling_agent.py

run-agent:
	uv run chapter-4/agent.py